import yaml
from tqdm import tqdm


def main() -> None:
    langs = ["zh", "es", "fr", "de", "ru", "ja", "th", "te", "sw", "bn", "ar", "ko", "vi", "cs", "hu", "sr"]

    for lang in tqdm(langs):
        file_name = f"xifeval_{lang}.yaml"
        try:
            with open(f"{file_name}", "w") as f:
                f.write("# Generated by _generate_configs.py\n")
                yaml.dump(
                    {
                        "dataset_kwargs": {
                            "data_files": f"/cpfs01/shared/XNLP_H800/huangxu/xeval/data/ifeval/ifeval_human_{lang}.jsonl",
                        },
                        "include": f"_default_template_yaml",
                        "task": f"xifeval_{lang}",
                    },
                    f,
                )
        except FileExistsError:
            pass


if __name__ == "__main__":
    main()
